<?php
return array(
    // this is displayed in the header section
    'title' => 'APHRIS System',
    'subtitle' => 'HR Integrated System',
    // this is used in error pages
    'adminName' => 'APHRIS Team HR Directorate',
    'adminEmail' => 'hrd@agungpodomoro.com',
    'adminHp' => '+6221 123 34567',
    'userEmail' => 'hrd@agungpodomoro.com',
    'twittername' => 'agungpodomoro',
    'twitterdisplay' => 'Agung Podomoro Land, Tbk',
    'appVersion' => '3.0.5',
    'custom1' => 'APL Tbk',
    'custom2' => 'PT Agung Podomoro Land Tbk',
    'parent_organization_filter' => 'parent_id = 0 AND id = 5',
    'currentYearMassLeaveLebaran' => 3,
    'currentYearMassLeaveChristmas' => 4,
    'currentYearMassLeave' => 9,
    'currentYearPrivateLeave' => 3,
    'currentYearLebaranStart' => '2014-07-30',
    'currentYearLebaranEnd' => '2014-08-01',
    'currentYearChristmasStart' => '2014-12-26',
    'currentYearChristmasEnd' => '2014-12-31',
    'webcareer' => 'http://www.agungpodomoro-career.com',
    'selfregistration'=>true,
    'broadcastPassword'=>'',
    'peterPassword'=>'',
    'performancePeriodStart'=>'2011',
);
